In [1]:
print("Hellow World")

Hellow World


In [3]:
import numpy as np

# Arrays

In [8]:
a = np.arange(15).reshape(3,5)
# a = np.arange(15)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
print("shape vs dimension",a.shape,"vs ",a.ndim)
print("item size:", a.itemsize) #size in bytes of each element
print("size:",a.size)


shape vs dimension (3, 5) vs  2
item size: 8
size: 15


In [13]:
b = np.array([6,7,8])
b


array([6, 7, 8])

## Array creation

In [20]:
a = np.array([2,3,4])
b = np.array([1.2,3.4,5.6])
print(a.dtype,b.dtype)

int64 float64


When creating arrays using the arange functions using floating point argument, the number of elements mght not be known due to some precision with  decimals, so it's prefereable to use `np.linspace`

In [30]:
A = np.array([[1,1],
              [0,1]])

B = np.array([[2,0],
              [3,4]])

print( A*B )
print( A@B ) #this si the dot product of A and B
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [8]:
import numpy as np
arr = np.random.randn(5, 3)
# compute the mean of each column, no loop
col_mean = arr.mean(axis=0)
print(col_mean)
# compute the mean of each row, no loop
row_mean = arr.mean(axis=1)
print(row_mean)
# normalize the array (subtract mean, divide by std)
col_std = arr.std(axis=0)
normalized = (arr - col_mean) / col_std
print("normalized array:", normalized)

[ 0.05388375 -0.64462922 -0.17098262]
[ 0.25353483 -0.51327181  0.4591926  -0.9937323  -0.47527014]
normalized array: [[ 0.06981824 -0.20971419  1.40497159]
 [-0.68258921  0.86888136 -0.6925249 ]
 [-0.0432149   0.85473475  1.02067683]
 [-1.14036859  0.32113625 -0.82898293]
 [ 1.79635446 -1.83503819 -0.90414058]]


some correction on the above.

Initially thought that computing the mean of each column will mean `axis=1` since 1 refers to column, but looking at it:
    - in order to get the mean of each column we need to compute the values across all the rows on each column, that makes `axis=0`