In [1]:
print("Hellow World")

Hellow World


In [1]:
import numpy as np

# Arrays

In [8]:
a = np.arange(15).reshape(3,5)
# a = np.arange(15)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
print("shape vs dimension",a.shape,"vs ",a.ndim)
print("item size:", a.itemsize) #size in bytes of each element
print("size:",a.size)


shape vs dimension (3, 5) vs  2
item size: 8
size: 15


In [13]:
b = np.array([6,7,8])
b


array([6, 7, 8])

## Array creation

In [20]:
a = np.array([2,3,4])
b = np.array([1.2,3.4,5.6])
print(a.dtype,b.dtype)

int64 float64


When creating arrays using the arange functions using floating point argument, the number of elements mght not be known due to some precision with  decimals, so it's prefereable to use `np.linspace`

In [30]:
A = np.array([[1,1],
              [0,1]])

B = np.array([[2,0],
              [3,4]])

print( A*B )
print( A@B ) #this si the dot product of A and B
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
